const {
  REACT_APP_CLIENT_ID,
  REACT_APP_CLIENT_SECRET,
  REACT_APP_PROXY_URL
} = process.env;

export default {
  CLIENT_ID: REACT_APP_CLIENT_ID,
  CLIENT_SECRET: REACT_APP_CLIENT_SECRET,
  PROXY_URL: REACT_APP_PROXY_URL
};
